"""empty message

Revision ID: 6ecaf8dfef38
Revises: 70554956fe31
Create Date: 2018-09-03 13:15:54.895173

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ecaf8dfef38'
down_revision = '70554956fe31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('offer', sa.Column('offer_desc', sa.String(length=255), nullable=False))
    op.add_column('offer', sa.Column('offer_end', sa.DateTime(), nullable=True))
    op.add_column('offer', sa.Column('offer_start', sa.DateTime(), nullable=True))
    op.add_column('product', sa.Column('product_desc', sa.String(length=255), nullable=False))
    op.add_column('product', sa.Column('product_image_url_l', sa.String(length=255), nullable=True))
    op.add_column('product', sa.Column('product_image_url_m', sa.String(length=255), nullable=True))
    op.add_column('product', sa.Column('product_image_url_s', sa.String(length=255), nullable=True))
    op.add_column('product', sa.Column('product_url', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'product_url')
    op.drop_column('product', 'product_image_url_s')
    op.drop_column('product', 'product_image_url_m')
    op.drop_column('product', 'product_image_url_l')
    op.drop_column('product', 'product_desc')
    op.drop_column('offer', 'offer_start')
    op.drop_column('offer', 'offer_end')
    op.drop_column('offer', 'offer_desc')
    # ### end Alembic commands ###
