"""product table

Revision ID: 70554956fe31
Revises: 
Create Date: 2018-09-03 09:36:43.087543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70554956fe31'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer',
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('offer_code', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('offer_id'),
    sa.UniqueConstraint('offer_code')
    )
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_code')
    )
    op.create_table('offer_link',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.offer_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer_link')
    op.drop_table('product')
    op.drop_table('offer')
    # ### end Alembic commands ###
