"""empty message

Revision ID: bcf9d03f3104
Revises: 
Create Date: 2018-09-10 10:34:14.190661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcf9d03f3104'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offer',
    sa.Column('offer_id', sa.Integer(), nullable=False),
    sa.Column('offer_code', sa.String(length=20), nullable=False),
    sa.Column('offer_name', sa.String(length=150), nullable=False),
    sa.Column('offer_desc', sa.String(length=255), nullable=True),
    sa.Column('offer_start', sa.DateTime(), nullable=False),
    sa.Column('offer_end', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('offer_id'),
    sa.UniqueConstraint('offer_code')
    )
    op.create_table('product',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('product_code', sa.String(length=20), nullable=True),
    sa.Column('product_desc', sa.String(length=255), nullable=False),
    sa.Column('product_image_url_s', sa.String(length=255), nullable=True),
    sa.Column('product_image_url_m', sa.String(length=255), nullable=True),
    sa.Column('product_image_url_l', sa.String(length=255), nullable=True),
    sa.Column('product_url', sa.String(length=50), nullable=True),
    sa.Column('product_lvl1', sa.String(length=50), nullable=True),
    sa.Column('product_lvl2', sa.String(length=50), nullable=True),
    sa.Column('product_lvl3', sa.String(length=50), nullable=True),
    sa.Column('product_lvl4', sa.String(length=50), nullable=True),
    sa.Column('product_lvl5', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('product_id'),
    sa.UniqueConstraint('product_code')
    )
    op.create_table('offer_link',
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('offer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['offer_id'], ['offer.offer_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['product.product_id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('offer_link')
    op.drop_table('product')
    op.drop_table('offer')
    # ### end Alembic commands ###
